version: "3.9"
services:
  notification:
    image: kambang/kingscorp:notification
    container_name: notification
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
      - 7001:7001
    volumes:
      - ./:/usr/src/app
    # env_file: ./.env
    command: npm run start
