/* eslint-disable prettier/prettier */
export enum MICROSERVICES {
    NOTIFICATIONS = "NOTIFICATIONS",
    CORE = "CORE",
    STATISTICS = "STATISTICS"
}

export enum MICROSERVICE_EVENTS {
    USER_CREATION = "USER_CREATION",
    PRODUCT_THRESHOLD_REACHED = "PRODUCT_THRESHOLD_REACHED",
    STOCK_UPDATE = "STOCK_UPDATE",
    PURCHASE_MADE = "PURCHASE_MADE",
    SALES_STATS = "SALES_STATS",
    STOCK_STATS = "STOCK_STATS",
    PRODUCTS_STATS = "PRODUCTS_STATS",
    CUSTOMER_STATS = "CUSTOMER_STATS",
    EMPLOYEE_STATS = "EMPLOYEE_STATS"
} 